<!DOCTYPE HTML>
<html>
<head>
    <title>Blogging Platform</title>
    <link href="/template/css/bootstrap.css" rel='stylesheet' type='text/css'/>
    <link href="/template/css/style.css" rel='stylesheet' type='text/css'/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design"
    />
    <script type="application/x-javascript"> addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);
        function hideURLbar() {
            window.scrollTo(0, 1);
        } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet'
          type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->
    <script type="text/javascript" src="/temolate/js/move-top.js"></script>
    <script type="text/javascript" src="/template/js/easing.js"></script>
    <!--/script-->
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 900);
            });
        });
    </script>
    <!---->

</head>
<body>
<!---header---->
<div class="header">
    <div class="container">
        <div class="logo">
            <a href="/"><img src="/template/images/logo.jpg" title=""/></a>
        </div>
        <!---start-top-nav---->
        <div class="top-menu">
            <div class="search">
                <form method="post" action="/post/search">
                    <input type="text" name="search" placeholder="поиск" required="">
                    <input type="submit" name="submit" value=""/>
                </form>
            </div>
            <span class="menu"> </span>
            <ul>
                <li class="active"><a href="/">ГЛАВНАЯ</a></li>
                <li><a href="/about">О БЛОГЕ</a></li>
                <li><a href="/contact">СВЯЗАТЬСЯ</a></li>
                <div class="clearfix"></div>
            </ul>
        </div>
        <div class="clearfix"></div>
        <script>
            $("span.menu").click(function () {
                $(".top-menu ul").slideToggle("slow", function () {
                });
            });
        </script>
        <!---//End-top-nav---->
    </div>
</div>
<!--/header-->
<!-- page content -->
<?= $this->content ?>
<!---->
<div class="footer">
    <div class="container">
        <p>Copyrights © <?= date('Y') ?> Blog All rights reserved | Template by <a href="http://w3layouts.com/">W3layouts</a>
        </p>
    </div>
</div>

</body>

</html>